#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Balance transfer sample
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'hlf_multi_host_network'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:8443','localhost:9443','localhost:9444',
		'ip-172-31-11-143:8444','ip-172-31-11-143:9445','ip-172-31-11-143:9446',
		'ip-172-31-1-154:8445','ip-172-31-1-154:9447','ip-172-31-1-154:9448']
    - targets: ['orderer1.example.com:8443','peer0.org1.example.com:9443','peer1.org1.example.com:9444',
		'orderer2.example.com:8444','peer0.org2.example.com:9445','peer1.org2.example.com:9446',
		'orderer3.example.com:8445','peer0.org3.example.com:9447','peer1.org3.example.com:9448']
      #- targets: [‘peer0.org1.example.com:9443’, ‘peer1.org1.example.com:9444’, ‘peer0.org2.example.com:9445’, ‘peer1.org2.example.com:9446’, ‘orderer.example.com:8443’]
